AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation para desplegar el microservicio DevOps en ECS Fargate,
  con un Application Load Balancer y un repositorio ECR.

Parameters:
  VpcId:
    Description: VPC donde se desplegará la infraestructura.
    Type: AWS::EC2::VPC::Id
    Default: "vpc-0a3cc45af634519e1"

  SubnetIds:
    Description: Lista de subnets públicas para el ALB y las tareas ECS (separadas por comas).
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-0b8f275103c982223,subnet-0b5323f1b9dfdd345,subnet-0fc4290294875884f"

  ContainerPort:
    Description: Puerto en el que la aplicación escucha en el contenedor.
    Type: Number
    Default: 8000

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: microservicio-devops

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MicroservicioDevOpsCluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MicroservicioDevOpsTask
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: MicroservicioDevOpsContainer
          Image: !Sub "${ECRRepository.RepositoryUri}:latest"
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Essential: true

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Seguridad para el Load Balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Seguridad para las tareas ECS del microservicio
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MicroservicioDevOpsLB
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MicroservicioDevOpsTG
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: /health
      Matcher:
        HttpCode: 200

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      ServiceName: MicroservicioDevOpsService
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref ServiceSecurityGroup
      LoadBalancers:
        - ContainerName: MicroservicioDevOpsContainer
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

Outputs:
  LoadBalancerDNS:
    Description: DNS del Load Balancer para acceder al microservicio
    Value: !GetAtt LoadBalancer.DNSName

  ECRRepositoryUri:
    Description: URI del repositorio ECR creado
    Value: !GetAtt ECRRepository.RepositoryUri
